
#Server side blocks configs
[blocks]

	[blocks.wall_lantern]
		#allow wall lanterns placement
		enabled = true

	[blocks.turn_table]
		#how many ticks it takes to rotate a block/entity
		#Range: 1 ~ 256
		period = 20

	[blocks.speaker_block]
		#maximum range
		#Range: 0 ~ 256
		range = 64

	[blocks.spring_launcher]
		#fall distance needed to trigger the automatic spring launch
		#Range: 0 ~ 512
		fall_height_required = 5
		#spring launcher launch speed
		#Range: 0.0 ~ 16.0
		velocity = 1.5

	[blocks.bellows]
		#velocity increase uses this equation: 
		#vel = base_vel*((range-entity_distance)/range) with base_vel = base_velocity_scaling/period 
		#note that the block will push further the faster it's pulsing
		#Range: 0.0 ~ 64.0
		base_velocity_scaling = 5.0
		#bellows pushes air following this equation: 
		#air=(sin(2PI*ticks/period)<0), with period = base_period-(redstone_power-1)*power_scaling 
		#represents base period at 1 power
		#Range: 1 ~ 512
		base_period = 78
		#note that it will still only keep alive the two fire blocks closer to it
		#Range: 0 ~ 16
		range = 5
		#entities with velocity greated than this won't be pushed
		#Range: 0.0 ~ 16.0
		power_scaling = 2.0
		#sets velocity changed flag when pushing entities +
		#causes pushing animation to be smooth client side but also restricts player movement when being pushed
		velocity_changed_flag = true

	[blocks.notice_board]
		#allow notice boards to accept and display any item, not just maps and books
		allow_any_item = false

	[blocks.jar]
		#catchable mobs
		mobs = ["minecraft:slime", "minecraft:parrot", "minecraft:bee", "minecraft:magma_cube"]
		#tinted jar catchable mobs
		tinted_jar_mobs = ["minecraft:endermite", "minecraft:slime", "minecraft:parrot", "minecraft:bee", "minecraft:magma_cube", "minecraft:vex"]
		#jar liquid capacity: leave at 12 for pixel accuracy
		#Range: 0 ~ 1024
		capacity = 12

#Configure spawning conditions
[spawns]

	[spawns.firefly]
		#Minimum group size
		#Range: 0 ~ 64
		min = 5
		#Spawnable biomes
		biomes = ["minecraft:swamp", "minecraft:swamp_hills", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:dark_forest", "minecraft:dark_forest_hills"]
		#Maximum group size
		#Range: 0 ~ 64
		max = 9
		#Spawn weight 
		#Set to 0 to disable spawning entirely
		#Range: 0 ~ 100
		weight = 3

