
#Weapon Throw Mod Configuration Settings
[general]
	#Weapon Cant be thrown if it is on cooldown
	"Not Throw If Cooldown" = true

#Client Settings
[client]
	#Charging Y Hud Offset
	#Range: -32 ~ 32
	Ycoord = 20
	#Charging X Hud Offset
	#Range: -32 ~ 32
	Xcoord = -8

#If an item is whitelisted and doesn't have damage or attack speed, this values will be assigned
[default]
	#Range: 0.0 ~ 256.0
	"Default Base Damage" = 1.0
	#Range: 0.0 ~ 256.0
	"Default Base Velocity" = 0.5

[enchantments]
	#Should Conccusion Enchantment be applied on survival?
	"Enable Conccusion Enchantment" = true
	#Should Throw Enchantment be applied on survival?
	"Enable Throw Enchantment" = true
	#Should gravity curse drop after some time?
	"Gravity Drop" = false
	#Should Grounded Edge Enchantment be applied on survival?
	"Enable Grounded Edge Enchantment" = true
	#Should Gravity Enchantment be applied on survival?
	"Enable Gravity Enchantment" = true
	#Should Return Enchantment be applied on survival?
	"Enable Return Enchantment" = true

[experimental]
	#Enable using all items as a weapon
	"Throw all items" = false

[fixes]
	#Disable this if theres tossing bugs
	"Item Physics Fix" = true

[interactions]
	#Throwing can break blocks at landing?
	"Break Blocks" = true

[multipliers]
	#Range: 0.0 ~ 256.0
	"Modified Exhaustion Multiplier" = 2.0
	#Range: 0.0 ~ 64.0
	"Stack Size Velocity Multiplier" = 0.005
	#Range: 0.0 ~ 256.0
	"Base Exhaustion Multiplier" = 0.075
	#Range: 0.0 ~ 64.0
	"Modified Velocity Multiplier" = 1.0
	#Range: 0.0 ~ 64.0
	"Base Velocity Multiplier" = 0.25
	#Range: 0.0 ~ 256.0
	"Modified Damage Multiplier" = 1.0
	#Range: 0.0 ~ 256.0
	"Stack Size Exhaustion Multiplier" = 0.01
	#Range: 0.0 ~ 256.0
	"Base Damage Multiplier" = 0.25
	#Range: 0.0 ~ 256.0
	"Stack Size Damage Multiplier" = 0.0

[time]
	#Attack Speed Multiplier to charging
	#Range: > 0
	"Charging Multiplier" = 3
	#Time in ticks when the throwed items should dissapear
	#Range: > 0
	"Despawn Time" = 1200
	#Time in ticks when throwed items lose their owner
	#Range: > 0
	"Lose Owner Time" = 140

#All Items Whitelisted will get default values
[whitelist-items]
	"Whitelisted items" = ["minecraft:brick", "minecraft:glass"]

#All Blacklisted blocks cannot be destroyed
[blacklist-blocks]
	"Blacklisted blocks" = ["minecraft:bedrock"]

